# Generated by Django 5.0.6 on 2024-08-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_figura', models.TextField(max_length=200)),
                ('personaje', models.TextField(max_length=40)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('fabricante', models.TextField(max_length=60)),
                ('precio', models.IntegerField()),
                ('tamaño', models.IntegerField()),
                ('material', models.TextField(max_length=30)),
                ('accesorios', models.TextField(max_length=600)),
                ('categoria', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.TextField(max_length=30)),
                ('contraseña_usuario', models.TextField(max_length=30)),
            ],
        ),
    ]
